// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8myBMHcWNWF7RlJH7aCR-sSmFHrhdMQA',
    appId: '1:741099713283:web:f0f4ef29791cdebf17af36',
    messagingSenderId: '741099713283',
    projectId: 'backend-firebase-bb332',
    authDomain: 'backend-firebase-bb332.firebaseapp.com',
    databaseURL: 'https://backend-firebase-bb332-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-firebase-bb332.firebasestorage.app',
    measurementId: 'G-219X7VP87Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L1WkkLiAvIh6YMecJ5P9RxMv8PIu19w',
    appId: '1:741099713283:android:55c581c85a08bfcb17af36',
    messagingSenderId: '741099713283',
    projectId: 'backend-firebase-bb332',
    databaseURL: 'https://backend-firebase-bb332-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-firebase-bb332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORt-cLfkQCerSvAr8TuDJcGsCD3wA5cw',
    appId: '1:741099713283:ios:fe576ee71d2d732c17af36',
    messagingSenderId: '741099713283',
    projectId: 'backend-firebase-bb332',
    databaseURL: 'https://backend-firebase-bb332-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-firebase-bb332.firebasestorage.app',
    iosBundleId: 'com.example.psyconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORt-cLfkQCerSvAr8TuDJcGsCD3wA5cw',
    appId: '1:741099713283:ios:fe576ee71d2d732c17af36',
    messagingSenderId: '741099713283',
    projectId: 'backend-firebase-bb332',
    databaseURL: 'https://backend-firebase-bb332-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-firebase-bb332.firebasestorage.app',
    iosBundleId: 'com.example.psyconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8myBMHcWNWF7RlJH7aCR-sSmFHrhdMQA',
    appId: '1:741099713283:web:baf41f95df3e398f17af36',
    messagingSenderId: '741099713283',
    projectId: 'backend-firebase-bb332',
    authDomain: 'backend-firebase-bb332.firebaseapp.com',
    databaseURL: 'https://backend-firebase-bb332-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-firebase-bb332.firebasestorage.app',
    measurementId: 'G-E96R23QF87',
  );
}
